package com.apollo.dto.doctor;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Request payload to unlock a patient's vault using their 6-digit consultation access PIN")
public class UnlockVaultRequest {

    @NotBlank(message = "Access code is required")
    @Pattern(regexp = "^\\d{6}$", message = "Access code must be a 6-digit numeric string")
    @Schema(example = "482910", description = "The 6-digit temporary PIN generated by the patient")
    private String accessCode;
}
